### ISSUE TITLE
Theme compile failed after switch to 0.9.10

### ISSUE THREAD

**Issue by livotov** [appreciated/vaadin-app-layout#40]
Just switched from older 0.9.3 and now getting theme compilation error
Vaadin 8.6.1, standard Valo theme (no customizations)

If I just switch back to 0.9.3 - it works again.

Any hint what could be wrong ?

Thanks,
Dmitri

```
ERROR] Exception in thread "main" java.lang.NullPointerException
[ERROR] at com.vaadin.sass.internal.util.ColorUtil.adjust(ColorUtil.java:575)
[ERROR] at com.vaadin.sass.internal.util.ColorUtil.lighten(ColorUtil.java:588)
[ERROR] at com.vaadin.sass.internal.parser.function.LightenFunctionGenerator.computeForArgumentList(LightenFunctionGenerator.java:42)
[ERROR] at com.vaadin.sass.internal.parser.function.AbstractFunctionGenerator.compute(AbstractFunctionGenerator.java:72)
[ERROR] at com.vaadin.sass.internal.parser.LexicalUnitImpl.evaluateFunctionsAndExpressions(LexicalUnitImpl.java:826)
[ERROR] at com.vaadin.sass.internal.tree.VariableNode.traverse(VariableNode.java:84)
[ERROR] at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:227)
[ERROR] at com.vaadin.sass.internal.tree.controldirective.TemporaryNode.traverseChildren(TemporaryNode.java:53)
[ERROR] at com.vaadin.sass.internal.visitor.ImportNodeHandler.traverse(ImportNodeHandler.java:97)
[ERROR] at com.vaadin.sass.internal.tree.ImportNode.traverse(ImportNode.java:99)
[ERROR] at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:227)
[ERROR] at com.vaadin.sass.internal.tree.controldirective.TemporaryNode.traverseChildren(TemporaryNode.java:53)
[ERROR] at com.vaadin.sass.internal.visitor.ImportNodeHandler.traverse(ImportNodeHandler.java:97)
[ERROR] at com.vaadin.sass.internal.tree.ImportNode.traverse(ImportNode.java:99)
[ERROR] at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:227)
[ERROR] at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:214)
[ERROR] at com.vaadin.sass.internal.ScssStylesheet.traverse(ScssStylesheet.java:298)
[ERROR] at com.vaadin.sass.internal.ScssStylesheet.compile(ScssStylesheet.java:267)
[ERROR] at com.vaadin.sass.SassCompiler.main(SassCompiler.java:101)
[ERROR] Exception in thread "main" java.lang.NullPointerException
[ERROR] at com.vaadin.sass.internal.util.ColorUtil.adjust(ColorUtil.java:575)
[ERROR] at com.vaadin.sass.internal.util.ColorUtil.lighten(ColorUtil.java:588)
[ERROR] at com.vaadin.sass.internal.parser.function.LightenFunctionGenerator.computeForArgumentList(LightenFunctionGenerator.java:42)
[ERROR] at com.vaadin.sass.internal.parser.function.AbstractFunctionGenerator.compute(AbstractFunctionGenerator.java:72)
[ERROR] at com.vaadin.sass.internal.parser.LexicalUnitImpl.evaluateFunctionsAndExpressions(LexicalUnitImpl.java:826)
[ERROR] at com.vaadin.sass.internal.tree.VariableNode.traverse(VariableNode.java:84)
[ERROR] at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:227)
[ERROR] at com.vaadin.sass.internal.tree.controldirective.TemporaryNode.traverseChildren(TemporaryNode.java:53)
[ERROR] at com.vaadin.sass.internal.visitor.ImportNodeHandler.traverse(ImportNodeHandler.java:97)
[ERROR] at com.vaadin.sass.internal.tree.ImportNode.traverse(ImportNode.java:99)
[ERROR] at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:227)
[ERROR] at com.vaadin.sass.internal.tree.controldirective.TemporaryNode.traverseChildren(TemporaryNode.java:53)
[ERROR] at com.vaadin.sass.internal.visitor.ImportNodeHandler.traverse(ImportNodeHandler.java:97)
[ERROR] at com.vaadin.sass.internal.tree.ImportNode.traverse(ImportNode.java:99)
[ERROR] at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:227)
[ERROR] at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:214)
[ERROR] at com.vaadin.sass.internal.ScssStylesheet.traverse(ScssStylesheet.java:298)
[ERROR] at com.vaadin.sass.internal.ScssStylesheet.compile(ScssStylesheet.java:267)
[ERROR] at com.vaadin.sass.SassCompiler.main(SassCompiler.java:101)
```

**Comment by appreciated** [comment]
Might be related to #31

**Comment by livotov** [comment]
Thanks for the quick response!

my addons.scss is as follows:

```
/* This file is automatically managed and will be overwritten from time to time. */
/* Do not manually edit this file. */

/* Provided by app-layout-addon-0.9.10.jar */
@import "../../../VAADIN/addons/app-layout/app-layout.scss";


/* Provided by md-stepper-2.2.jar */
@import "../../../VAADIN/addons/md_stepper/scss/md-stepper.scss";


/* Provided by spinkit-1.0.0.jar */
@import "../../../VAADIN/addons/spinkit/spinkit.scss";


/* Import and include this mixin into your project theme to include the addon themes */
@mixin addons {
	@include app-layout;
	@include md-stepper;
	@include spinkit;
}
```

and theme file is just

```
@import "../valo/valo.scss";

@mixin monetka {
	@include valo;
}
```

**Comment by livotov** [comment]
Interesting finding: 

- If I downgrade the addon version to 0.9.8 - everything works fine.
- On 0.9.9 and 0.9.10 I'm getting the same theme compilation error as posted above

**Comment by livotov** [comment]
P.S. I'm not using maven but using gradle with the vaadin gradle plugin, in case this is important

**Comment by appreciated** [comment]
Can you do this and check if it changes anything? 

> gradle build --refresh-dependencies

Version 0.9.9 should not be available anymore since it has a bug.

**Comment by livotov** [comment]
Yep, did this already, also cleaned up my grade/.cache folder too - but with the same result - 0.9.10 does not work, 0.9.8 is ok and also still can download 0.9.9 ( I do see downloading progress, so it comes not from the cache)

**Comment by appreciated** [comment]
Hmm I really don't know how I can help you with this, For me compiling the sass works with 0.9.10. 

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building test 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://maven.vaadin.com/vaadin-addons/com/github/appreciated/app-layout-addon/0.9.10/app-layout-addon-0.9.10.pom
Downloaded: http://maven.vaadin.com/vaadin-addons/com/github/appreciated/app-layout-addon/0.9.10/app-layout-addon-0.9.10.pom (11 KB at 11.6 KB/sec)
Downloading: http://maven.vaadin.com/vaadin-addons/com/github/appreciated/app-layout-addon/0.9.10/app-layout-addon-0.9.10.jar
Downloaded: http://maven.vaadin.com/vaadin-addons/com/github/appreciated/app-layout-addon/0.9.10/app-layout-addon-0.9.10.jar (2152 KB at 910.4 KB/sec)
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ test ---
[INFO] Deleting C:\Users\Johannes\IdeaProjects\app-layout-test\target
[INFO] Deleting C:\Users\Johannes\IdeaProjects\app-layout-test\src\main\webapp\VAADIN\themes (includes = [**/styles.css, **/styles.scss.cache], excludes = [])
[INFO] 
[INFO] --- vaadin-maven-plugin:8.1.5:update-theme (default) @ test ---
[INFO] Updating theme VAADIN\themes\mytheme
[INFO] Widgetsets found from classpath:
[INFO] Addon styles found from classpath:
[INFO] 	VAADIN/addons/app-layout/app-layout.scss in jar:file:C:/Users/Johannes/.m2/repository/com/github/appreciated/app-layout-addon/0.9.10/app-layout-addon-0.9.10.jar!/
[INFO] 
[INFO] Search took 11ms
[INFO] Theme "VAADIN\themes\mytheme" updated
[INFO] 
[INFO] --- vaadin-maven-plugin:8.1.5:update-widgetset (default) @ test ---
[WARNING] GWT plugin is configured to detect modules, but none were found.
[INFO] No widgetsets found - generating AppWidgetset if necessary.
[INFO] Updating widgetset AppWidgetset
[INFO] Adding resource directory to command classpath: C:\Users\Johannes\IdeaProjects\app-layout-test\src\main\resources
[INFO] Adding resource directory to command classpath: C:\Users\Johannes\IdeaProjects\app-layout-test\target\generated-resources\gwt
[INFO] Using com.vaadin:vaadin-client version 8.1.5
[INFO] Using com.vaadin:vaadin-client-compiler version 8.1.5
[INFO] Widgetsets found from classpath:
[INFO] 	com.vaadin.DefaultWidgetSet in jar:file:C:/Users/Johannes/.m2/repository/com/vaadin/vaadin-client/8.1.5/vaadin-client-8.1.5.jar!/
[INFO] Addon styles found from classpath:
[INFO] 	VAADIN/addons/app-layout/app-layout.scss in jar:file:C:/Users/Johannes/.m2/repository/com/github/appreciated/app-layout-addon/0.9.10/app-layout-addon-0.9.10.jar!/
[INFO] 
[INFO] Search took 10ms
[INFO] 
[INFO] --- vaadin-maven-plugin:8.1.5:compile-theme (default) @ test ---
[INFO] Updating theme VAADIN\themes\mytheme
[INFO] Theme "VAADIN\themes\mytheme" compiled
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ test ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to C:\Users\Johannes\IdeaProjects\app-layout-test\target\classes
[INFO] 
[INFO] --- vaadin-maven-plugin:8.1.5:compile (default) @ test ---
[WARNING] GWT plugin is configured to detect modules, but none were found.
[INFO] Using com.vaadin:vaadin-client version 8.1.5
[INFO] Using com.vaadin:vaadin-client-compiler version 8.1.5
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\Johannes\IdeaProjects\app-layout-test\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ test ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ test ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-war-plugin:3.0.0:war (default-war) @ test ---
[INFO] Packaging webapp
[INFO] Assembling webapp [test] in [C:\Users\Johannes\IdeaProjects\app-layout-test\target\test-1.0-SNAPSHOT]
[INFO] Processing war project
[INFO] Copying webapp resources [C:\Users\Johannes\IdeaProjects\app-layout-test\src\main\webapp]
[INFO] Webapp assembled in [2025 msecs]
[INFO] Building war: C:\Users\Johannes\IdeaProjects\app-layout-test\target\test-1.0-SNAPSHOT.war
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ test ---
[INFO] Installing C:\Users\Johannes\IdeaProjects\app-layout-test\target\test-1.0-SNAPSHOT.war to C:\Users\Johannes\.m2\repository\com\app\layout\test\1.0-SNAPSHOT\test-1.0-SNAPSHOT.war
[INFO] Installing C:\Users\Johannes\IdeaProjects\app-layout-test\pom.xml to C:\Users\Johannes\.m2\repository\com\app\layout\test\1.0-SNAPSHOT\test-1.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 33.367 s
[INFO] Finished at: 2017-10-29T14:56:35+01:00
[INFO] Final Memory: 30M/278M
[INFO] ------------------------------------------------------------------------
```

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building test 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- vaadin-maven-plugin:8.1.5:compile-theme (default-cli) @ test ---
[INFO] Updating theme VAADIN\themes\mytheme
[INFO] Theme "VAADIN\themes\mytheme" compiled
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.454 s
[INFO] Finished at: 2017-10-29T14:57:05+01:00
[INFO] Final Memory: 15M/160M
[INFO] ------------------------------------------------------------------------
```

Since I'm not able to switch out the JAR in the Maven Respository It should not be possible that you have a different JAR then I have. Maybe you could compare the checksum of the [JAR that I downloaded]( http://maven.vaadin.com/vaadin-addons/com/github/appreciated/app-layout-addon/0.9.10/app-layout-addon-0.9.10.jar) and yours, this would explain it. 

I haven't got much experience with Gradle so I cannot really help you with it 🤔.

**Comment by livotov** [comment]
Yeah, interesting. However, as far as I can see from your gradle log above, you're using vaadin maven plugin for gradle and I'm using pure vaadin gradle plugin ( https://github.com/johndevs/gradle-vaadin-plugin ) - maybe this adds some difference.

I'll try to dig deeper into the 0.9.8 and 0.9.10 versions  that are being downloaded and see if I can find anything. Will let you know.

**Comment by appreciated** [comment]
Any Progress? 
> Can you please unpack your jar for me and give me the content of the following file?
> src\main\webapp\VAADIN\addons\app-layout\components\app-layout-flexbox.sass

**Comment by livotov** [comment]
sorry for delay, will do this tonight and let you know here, thanks!

**Comment by appreciated** [comment]
Does Version 0.9.11 change anything for you?

**Comment by livotov** [comment]
sorry, got overloaded with tasks last week.... here are the findings:

0.9.11 fails with the same exception (but including the latest stack trace just in case).
Also, attaching below the sass file extracted from the addon's app-layout-addon-0.9.11-sources.jar 

`
/**
 * Flexbox for Vaadin
 */

@mixin app-layout-flexbox {
  .v-csslayout {
    &.flex-row {
      @include display(flex);
      @include flex-direction(row);
    }
    &.flex-column {
      @include display(flex);
      @include flex-direction(column);
    }
    &.flex-row.overflow-auto {
      overflow-y: auto;
      overflow-x: hidden;
    }
    &.flex-column.overflow-auto {
      overflow-y: auto;
      overflow-x: hidden;
    }
    &.flex-row, .flex-column {
      :not(.shrink):not(.grow) {
        @include flex-grow(0);
        @include flex-shrink(0);
      }
      .grow:not(.shrink) {
        @include flex-grow(1);
      }
      .shrink:not(.grow) {
        @include flex-shrink(1);
        overflow: auto;
      }
      .grow.shrink {
        @include flex-grow(1);
        @include flex-shrink(1);
        overflow: auto;
      }
      .justify-flex-start {
        justify-content: flex-start;
      }
      .justify-center {
        justify-content: center;
      }
      .justify-flex-end {
        justify-content: flex-end;
      }
      .justify-space-between {
        justify-content: space-between;
      }
      .justify-space-around {
        justify-content: space-around;
      }
      .align-flex-start {
        align-items: flex-start;
      }
      .align-flex-end {
        align-items: flex-end;
      }
      .align-center {
        align-items: center;
      }
      .align-baseline {
        align-items: baseline;
      }
      .align-stretch {
        align-items: stretch;
      }
    }
  }
}
`


`
[ERROR] Exception in thread "main" java.lang.NullPointerException
[ERROR] at com.vaadin.sass.internal.util.ColorUtil.adjust(ColorUtil.java:575)
[ERROR] at com.vaadin.sass.internal.util.ColorUtil.lighten(ColorUtil.java:588)
[ERROR] at com.vaadin.sass.internal.parser.function.LightenFunctionGenerator.computeForArgumentList(LightenFunctionGenerator.java:42)
[ERROR] at com.vaadin.sass.internal.parser.function.AbstractFunctionGenerator.compute(AbstractFunctionGenerator.java:72)
[ERROR] at com.vaadin.sass.internal.parser.LexicalUnitImpl.evaluateFunctionsAndExpressions(LexicalUnitImpl.java:826)
[ERROR] at com.vaadin.sass.internal.tree.VariableNode.traverse(VariableNode.java:84)
[ERROR] at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:227)
[ERROR] at com.vaadin.sass.internal.tree.controldirective.TemporaryNode.traverseChildren(TemporaryNode.java:53)
[ERROR] at com.vaadin.sass.internal.visitor.ImportNodeHandler.traverse(ImportNodeHandler.java:97)
[ERROR] at com.vaadin.sass.internal.tree.ImportNode.traverse(ImportNode.java:99)
[ERROR] at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:227)
[ERROR] at com.vaadin.sass.internal.tree.controldirective.TemporaryNode.traverseChildren(TemporaryNode.java:53)
[ERROR] at com.vaadin.sass.internal.visitor.ImportNodeHandler.traverse(ImportNodeHandler.java:97)
[ERROR] at com.vaadin.sass.internal.tree.ImportNode.traverse(ImportNode.java:99)
[ERROR] at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:227)
[ERROR] at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:214)
[ERROR] at com.vaadin.sass.internal.ScssStylesheet.traverse(ScssStylesheet.java:298)
[ERROR] at com.vaadin.sass.internal.ScssStylesheet.compile(ScssStylesheet.java:267)
[ERROR] at com.vaadin.sass.SassCompiler.main(SassCompiler.java:101)
[ERROR] Exception in thread "main" java.lang.NullPointerException
[ERROR] at com.vaadin.sass.internal.util.ColorUtil.adjust(ColorUtil.java:575)
[ERROR] at com.vaadin.sass.internal.util.ColorUtil.lighten(ColorUtil.java:588)
[ERROR] at com.vaadin.sass.internal.parser.function.LightenFunctionGenerator.computeForArgumentList(LightenFunctionGenerator.java:42)
[ERROR] at com.vaadin.sass.internal.parser.function.AbstractFunctionGenerator.compute(AbstractFunctionGenerator.java:72)
[ERROR] at com.vaadin.sass.internal.parser.LexicalUnitImpl.evaluateFunctionsAndExpressions(LexicalUnitImpl.java:826)
[ERROR] at com.vaadin.sass.internal.tree.VariableNode.traverse(VariableNode.java:84)
[ERROR] at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:227)
[ERROR] at com.vaadin.sass.internal.tree.controldirective.TemporaryNode.traverseChildren(TemporaryNode.java:53)
[ERROR] at com.vaadin.sass.internal.visitor.ImportNodeHandler.traverse(ImportNodeHandler.java:97)
[ERROR] at com.vaadin.sass.internal.tree.ImportNode.traverse(ImportNode.java:99)
[ERROR] at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:227)
[ERROR] at com.vaadin.sass.internal.tree.controldirective.TemporaryNode.traverseChildren(TemporaryNode.java:53)
[ERROR] at com.vaadin.sass.internal.visitor.ImportNodeHandler.traverse(ImportNodeHandler.java:97)
[ERROR] at com.vaadin.sass.internal.tree.ImportNode.traverse(ImportNode.java:99)
[ERROR] at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:227)
[ERROR] at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:214)
[ERROR] at com.vaadin.sass.internal.ScssStylesheet.traverse(ScssStylesheet.java:298)
[ERROR] at com.vaadin.sass.internal.ScssStylesheet.compile(ScssStylesheet.java:267)
[ERROR] at com.vaadin.sass.SassCompiler.main(SassCompiler.java:101)
`

**Comment by livotov** [comment]
Oh, did not mention it seems - I'm also using the custom widgetset name (id) if this matters.

**Comment by appreciated** [comment]
Would you mind [joining me on slack](https://join.slack.com/t/vaadin-app-layout/shared_invite/enQtMjY4MTIzMTc2OTE4LWEwNTRjNzcyNzc4YmRlYWJmM2E0YTg1YWRkMDE3MmI1MzMxNWFlNWRlYjAwMTUxMzkwMmQ3MjJkYWU5ODMwY2I) some day so we can speed up the process?

**Comment by livotov** [comment]
Sure, joined

**Comment by livotov** [comment]
So, in summary, this could happen when you have undefined $v-background-color variable.
If anyone else is experiencing similar issue - simply add this to the very beginning of your
theme styles.scss file:

```
$v-background-color: #fafafa;
```

and it should work fine then.

@appreciated many thanks for your help!

**Comment by livotov** [comment]
upd, probably a bug in gradle-vaadin-plugin - just filed the issue there too.
https://github.com/johndevs/gradle-vaadin-plugin/issues/474

**Comment by appreciated** [comment]
I added a workaround for projects that were generated with the gradle plugin.

**Comment by appreciated** [comment]
Thank you very much for your help!
